"""Phonetic drug-name correction for ASR transcripts.

A fast on-device recogniser (Moonshine) has no medical vocabulary and mangles
drug names phonetically ("ripe fall" → propofol, "a trendal in" → adrenaline).
Since the formulary is small and fixed, we map mangled words back to canonical
drug names by SOUND, before parsing/extraction. This runs on the server for any
ASR-sourced utterance and works even without the LLM.

Two layers:
  1. ALIASES — an explicit, editable map of known (Australian-accent) mishears →
     canonical drug. Highest priority, fully deterministic. Extend as you observe
     real mishears.
  2. Phonetic fuzzy match (Metaphone + Jaro–Winkler) for near-misses not in the
     alias map ("metaramanol" → metaraminol, "fentonil" → fentanyl).

Conservative by design: numbers, short function words, and anything not clearly
drug-like are left untouched.
"""
from __future__ import annotations

import re

import jellyfish

from app.drugs import DRUGS

# --- Layer 1: known-mishear map (Australian-accent dictation) ---------------
# MANUAL_ALIASES: hand-curated, highest priority. GENERATED_ALIASES: produced by
# scripts/gen_aliases.py (TTS in AU voices → the actual Moonshine model). Final
# ALIASES merges them with manual overriding generated.
MANUAL_ALIASES: dict[str, str] = {
    "ripe fall": "propofol",
    "proper full": "propofol",
    "proper for": "propofol",
    "propofal": "propofol",
    "proponol": "propofol",
    "a trendal in": "adrenaline",
    "a trendaline": "adrenaline",
    "adrenal in": "adrenaline",
    "adrenalin": "adrenaline",
    "nor add": "noradrenaline",
    "more add": "noradrenaline",
    "noradrenalin": "noradrenaline",
    "rock uranium": "rocuronium",
    "rock you romeo": "rocuronium",
    "rocuronion": "rocuronium",
    "sucks": "suxamethonium",
    "sucks a methonium": "suxamethonium",
    "meta ram in all": "metaraminol",
    "metaraminal": "metaraminol",
    "metaramanol": "metaraminol",
    "fentonil": "fentanyl",
    "fenton ill": "fentanyl",
    "remy fentanyl": "remifentanil",
    "sugar madex": "sugammadex",
    "glyco pirate": "glycopyrrolate",
    "milra known": "milrinone",
    "dobu tam in": "dobutamine",
    "calcium chloride": "calcium chloride",
}

# Generated by scripts/gen_aliases.py (AU TTS → the real Moonshine model). Manual
# entries override generated ones. Missing file (e.g. fresh checkout) is fine.
try:
    from app.alias_generated import GENERATED_ALIASES
except Exception:  # noqa: BLE001
    GENERATED_ALIASES = {}

ALIASES: dict[str, str] = {**GENERATED_ALIASES, **MANUAL_ALIASES}
_MAX_ALIAS_WORDS = max((len(k.split()) for k in ALIASES), default=1)

# Common words that must never be "corrected" into a drug.
STOPWORDS = {
    "a", "an", "the", "of", "to", "up", "down", "in", "on", "at", "for", "and",
    "or", "now", "give", "given", "gave", "push", "stop", "start", "started",
    "is", "it", "i", "im", "we", "ok", "okay", "per", "kilo", "kig", "point",
    "milligram", "milligrams", "microgram", "micrograms", "unit", "units", "mil",
    "mls", "mil litres", "bolus", "infusion", "rate", "another", "same", "again",
    "go", "going", "off", "on", "with", "that", "this", "by", "her", "his", "him",
}

_JW_THRESHOLD = 0.88   # Jaro–Winkler similarity needed to accept a phonetic match
_MIN_LEN = 4           # don't fuzzy-match very short tokens (avoids function words)


def _norm(s: str) -> str:
    return re.sub(r"[^a-z\s]", "", s.lower()).strip()


def _meta(s: str) -> str:
    try:
        return jellyfish.metaphone(s)
    except Exception:  # noqa: BLE001
        return ""


# Phonetic index: canonical -> list of (name, metaphone) for canonical + longer synonyms.
_INDEX: dict[str, list[tuple[str, str]]] = {}
for _d in DRUGS:
    entries = [_d.canonical] + [s for s in _d.synonyms if len(s) >= _MIN_LEN]
    _INDEX[_d.canonical] = [(_norm(n), _meta(_norm(n))) for n in entries]


def _phonetic_match(token: str) -> str | None:
    """Single-token phonetic match to a canonical drug (or None)."""
    p = _norm(token)
    if not p or any(ch.isdigit() for ch in token):
        return None
    if p in ALIASES:
        return ALIASES[p]
    if p in STOPWORDS or len(p) < _MIN_LEN:
        return None
    code = _meta(p)
    best, best_score = None, 0.0
    for canon, entries in _INDEX.items():
        for name, ncode in entries:
            score = jellyfish.jaro_winkler_similarity(p, name)
            if code and ncode:
                score = max(score, jellyfish.jaro_winkler_similarity(code, ncode))
            if score > best_score:
                best, best_score = canon, score
    return best if best_score >= _JW_THRESHOLD else None


def correct_transcript(text: str) -> str:
    """Replace mangled drug words in an ASR transcript with canonical names.

    Multi-word mishears are corrected only via the exact ALIASES map (safe);
    single tokens may also match phonetically. This avoids a greedy window
    swallowing adjacent words like "up to".
    """
    tokens = text.split()
    out: list[str] = []
    i = 0
    while i < len(tokens):
        hit = None
        for n in range(_MAX_ALIAS_WORDS, 0, -1):  # multi-word: exact alias only
            if i + n <= len(tokens):
                window = tokens[i:i + n]
                if any(any(ch.isdigit() for ch in t) for t in window):
                    continue                       # never let an alias span a number
                phrase = _norm(" ".join(window))
                if phrase in ALIASES:
                    hit = (ALIASES[phrase], n)
                    break
        if not hit:                               # single token: phonetic match
            drug = _phonetic_match(tokens[i])
            if drug:
                hit = (drug, 1)
        if hit:
            out.append(hit[0])
            i += hit[1]
        else:
            out.append(tokens[i])
            i += 1
    return " ".join(out)

